const state = {
    OwnAppi1Name: "Nabídka 1",
    OwnAppi1Icon: "BellOutline",
    OwnAppi2Name: "Nabídka 2",
    OwnAppi2Icon: "BellOutline",
    OwnAppi3Name: "Nabídka 3",
    OwnAppi3Icon: "BellOutline",
    OwnAppi4Name: "Nabídka 4",
    OwnAppi4Icon: "BellOutline",
    OwnAppi5Name: "Nabídka 5",
    OwnAppi5Icon: "BellOutline",
    ShowLink: [true, true, true, true, true],
    ShowLinkNewWin: [true, true, true, true, true],
    ShowLinkBtn: [false, false, false, false, false],
    CycleShowing: [true, true, true, true, true],
    ownAppiActive: [false, false, false, false, false],
    editorContentCz: ["<span>Zaregistrujte se do našeho e-shopu a <strong>získejte 5% slevu</strong> na Váš nákup.</span>", "<span>Zaregistrujte se do našeho e-shopu a <strong>získejte 5% slevu</strong> na Váš nákup.</span>", "<span>Zaregistrujte se do našeho e-shopu a <strong>získejte 5% slevu</strong> na Váš nákup.</span>", "<span>Zaregistrujte se do našeho e-shopu a <strong>získejte 5% slevu</strong> na Váš nákup.</span>", "<span>Zaregistrujte se do našeho e-shopu a <strong>získejte 5% slevu</strong> na Váš nákup.</span>"],
    editorContentSk: ["<span> Zaregistrujte sa do nášho e-shopu a <strong> získajte 5% zľavu </ strong> na Váš nákup.</ span>", "<span> Zaregistrujte sa do nášho e-shopu a <strong> získajte 5% zľavu </ strong> na Váš nákup.</ span>", "<span> Zaregistrujte sa do nášho e-shopu a <strong> získajte 5% zľavu </ strong> na Váš nákup.</ span>", "<span> Zaregistrujte sa do nášho e-shopu a <strong> získajte 5% zľavu </ strong> na Váš nákup.</ span>", "<span>  Zaregistrujte sa do nášho e-shopu a <strong> získajte 5% zľavu </ strong> na Váš nákup.</ span>"],
    editorContentEn: ["<span> Sign up to our newsletter and <strong> get a 5% discount </strong> on your purchase. </span>", "<span> Sign up for our e-shop and <strong> get 5% discount </strong> on your purchase. </span>", " <span> Sign up to our newsletter and <strong> get a 5% discount </strong> on your purchase. </span>", "<span> Sign up to our newsletter and <strong> get a 5% discount </strong> on your purchase. </span>", "<span> Sign up to our newsletter and <strong> get 5 % off </strong> on your purchase. </span>"],
    zoomIcon: [50, 50, 50, 50, 50],
    horizontalIcon: [31, 31, 31, 31, 31],
    verticalIcon: [10, 10, 10, 10, 10],
    targetUrl: ["https://app.cz", "https://app.cz", "https://app.cz", "https://app.cz", "https://app.cz"],
    linkDescriptionCz: ["Klikněte a získejte dárek", "Klikněte a získejte dárek", "Klikněte a získejte dárek", "Klikněte a získejte dárek", "Klikněte a získejte dárek"],
    linkDescriptionSk: ["Kliknite a získajte darček", "Kliknite a získajte darček", "Kliknite a získajte darček", "Kliknite a získajte darček", "Kliknite a získajte darček"],
    linkDescriptionEn: ["Click here for a gift", "Click here for a gift", "Click here for a gift", "Click here for a gift", "Click here for a gift"],
    Iconcolor1: '#813EEF',
    Iconcolor2: '#813EEF',
    Iconcolor3: '#813EEF',
    Iconcolor4: '#813EEF',
    Iconcolor5: '#813EEF',
    IconcolorBtn1: '#813EEF',
    IconcolorBtn2: '#813EEF',
    IconcolorBtn3: '#813EEF',
    IconcolorBtn4: '#813EEF',
    IconcolorBtn5: '#813EEF',
    IconcolorBckBtn1: '#ffffff',
    IconcolorBckBtn2: '#ffffff',
    IconcolorBckBtn3: '#ffffff',
    IconcolorBckBtn4: '#ffffff',
    IconcolorBckBtn5: '#ffffff',
    showLastTopVariables: [20, 20, 20, 20, 20]
};

const getters = {
    OWNAppi_OwnAppi1Name: state => { return state.OwnAppi1Name = "Nabídka 1" },
    OWNAppi_OwnAppi1Icon: state => { return state.OwnAppi1Icon = "BellOutline" },
    OWNAppi_OwnAppi2Name: state => { return state.OwnAppi2Name = "Nabídka 2" },
    OWNAppi_OwnAppi2Icon: state => { return state.OwnAppi2Icon = "BellOutline" },
    OWNAppi_OwnAppi3Name: state => { return state.OwnAppi3Name = "Nabídka 3" },
    OWNAppi_OwnAppi3Icon: state => { return state.OwnAppi3Icon = "BellOutline" },
    OWNAppi_OwnAppi4Name: state => { return state.OwnAppi4Name = "Nabídka 4" },
    OWNAppi_OwnAppi4Icon: state => { return state.OwnAppi4Icon = "BellOutline" },
    OWNAppi_OwnAppi5Name: state => { return state.OwnAppi5Name = "Nabídka 5" },
    OWNAppi_OwnAppi5Icon: state => { return state.OwnAppi5Icon = "BellOutline" },
    OWNAppi_OwnAppiIcons: state => {
        return ["<svg fill='#813EEF' id='BellOutline' width='50' height='50' viewBox='0 0 24 24' xmlns='xmlns=&quot;http://www.w3.org/2000/svg&quot;'><path d='M16,17H7V10.5C7,8 9,6 11.5,6C14,6 16,8 16,10.5M18,16V10.5C18,7.43 15.86,4.86 13,4.18V3.5A1.5,1.5 0 0,0 11.5,2A1.5,1.5 0 0,0 10,3.5V4.18C7.13,4.86 5,7.43 5,10.5V16L3,18V19H20V18M11.5,22A2,2 0 0,0 13.5,20H9.5A2,2 0 0,0 11.5,22Z'></path></svg>",
            "<svg fill='#813EEF' id='BellOutline' width='50' height='50' viewBox='0 0 24 24' xmlns='xmlns=&quot;http://www.w3.org/2000/svg&quot;'><path d='M16,17H7V10.5C7,8 9,6 11.5,6C14,6 16,8 16,10.5M18,16V10.5C18,7.43 15.86,4.86 13,4.18V3.5A1.5,1.5 0 0,0 11.5,2A1.5,1.5 0 0,0 10,3.5V4.18C7.13,4.86 5,7.43 5,10.5V16L3,18V19H20V18M11.5,22A2,2 0 0,0 13.5,20H9.5A2,2 0 0,0 11.5,22Z'></path></svg>",
            "<svg fill='#813EEF' id='BellOutline' width='50' height='50' viewBox='0 0 24 24' xmlns='xmlns=&quot;http://www.w3.org/2000/svg&quot;'><path d='M16,17H7V10.5C7,8 9,6 11.5,6C14,6 16,8 16,10.5M18,16V10.5C18,7.43 15.86,4.86 13,4.18V3.5A1.5,1.5 0 0,0 11.5,2A1.5,1.5 0 0,0 10,3.5V4.18C7.13,4.86 5,7.43 5,10.5V16L3,18V19H20V18M11.5,22A2,2 0 0,0 13.5,20H9.5A2,2 0 0,0 11.5,22Z'></path></svg>",
            "<svg fill='#813EEF' id='BellOutline' width='50' height='50' viewBox='0 0 24 24' xmlns='xmlns=&quot;http://www.w3.org/2000/svg&quot;'><path d='M16,17H7V10.5C7,8 9,6 11.5,6C14,6 16,8 16,10.5M18,16V10.5C18,7.43 15.86,4.86 13,4.18V3.5A1.5,1.5 0 0,0 11.5,2A1.5,1.5 0 0,0 10,3.5V4.18C7.13,4.86 5,7.43 5,10.5V16L3,18V19H20V18M11.5,22A2,2 0 0,0 13.5,20H9.5A2,2 0 0,0 11.5,22Z'></path></svg>",
            "<svg fill='#813EEF' id='BellOutline' width='50' height='50' viewBox='0 0 24 24' xmlns='xmlns=&quot;http://www.w3.org/2000/svg&quot;'><path d='M16,17H7V10.5C7,8 9,6 11.5,6C14,6 16,8 16,10.5M18,16V10.5C18,7.43 15.86,4.86 13,4.18V3.5A1.5,1.5 0 0,0 11.5,2A1.5,1.5 0 0,0 10,3.5V4.18C7.13,4.86 5,7.43 5,10.5V16L3,18V19H20V18M11.5,22A2,2 0 0,0 13.5,20H9.5A2,2 0 0,0 11.5,22Z'></path></svg>"] },
    OWNAppi_ShowLink: state => { return state.ShowLink = [true, true, true, true, true] },
    OWNAppi_ShowLinkNewWin: state => { return state.ShowLinkNewWin = [true, true, true, true, true] },
    OWNAppi_ShowLinkBtn: state => { return state.ShowLinkBtn = [false, false, false, false, false] },
    OWNAppi_CycleShowing: state => { return state.CycleShowing = [true, true, true, true, true] },
    OWNAppi_ownAppiActive: state => { return state.ownAppiActive = [false, false, false, false, false] },
    OWNAppi_editorContentCz: state => { return state.editorContentCz = ["<span>Zaregistrujte se do našeho e-shopu a <strong>získejte 5% slevu</strong> na Váš nákup.</span>", "<span>Zaregistrujte se do našeho e-shopu a <strong>získejte 5% slevu</strong> na Váš nákup.</span>", "<span>Zaregistrujte se do našeho e-shopu a <strong>získejte 5% slevu</strong> na Váš nákup.</span>", "<span>Zaregistrujte se do našeho e-shopu a <strong>získejte 5% slevu</strong> na Váš nákup.</span>", "<span>Zaregistrujte se do našeho e-shopu a <strong>získejte 5% slevu</strong> na Váš nákup.</span>"] },
    OWNAppi_editorContentSk: state => { return state.editorContentSk = ["<span> Zaregistrujte sa do nášho e-shopu a <strong> získajte 5% zľavu </ strong> na Váš nákup.</ span>", "<span> Zaregistrujte sa do nášho e-shopu a <strong> získajte 5% zľavu </ strong> na Váš nákup.</ span>", "<span> Zaregistrujte sa do nášho e-shopu a <strong> získajte 5% zľavu </ strong> na Váš nákup.</ span>", "<span> Zaregistrujte sa do nášho e-shopu a <strong> získajte 5% zľavu </ strong> na Váš nákup.</ span>", "<span>  Zaregistrujte sa do nášho e-shopu a <strong> získajte 5% zľavu </ strong> na Váš nákup.</ span>"] },
    OWNAppi_editorContentEn: state => { return state.editorContentEn = ["<span> Sign up to our newsletter and <strong> get a 5% discount </strong> on your purchase. </span>", "<span> Sign up for our e-shop and <strong> get 5% discount </strong> on your purchase. </span>", " <span> Sign up to our newsletter and <strong> get a 5% discount </strong> on your purchase. </span>", "<span> Sign up to our newsletter and <strong> get a 5% discount </strong> on your purchase. </span>", "<span> Sign up to our newsletter and <strong> get 5 % off </strong> on your purchase. </span>"] },
    OWNAppi_zoomIcon: state => { return state.zoomIcon = [50, 50, 50, 50, 50] },
    OWNAppi_horizontalIcon: state => { return state.horizontalIcon = [31, 31, 31, 31, 31] },
    OWNAppi_verticalIcon: state => { return state.verticalIcon = [10, 10, 10, 10, 10] },
    OWNAppi_targetUrl: state => { return state.targetUrl = ["https://app.cz", "https://app.cz", "https://app.cz", "https://app.cz", "https://app.cz"]},
    OWNAppi_linkDescriptionCz: state => { return state.linkDescriptionCz = ["Klikněte a získejte dárek", "Klikněte a získejte dárek", "Klikněte a získejte dárek", "Klikněte a získejte dárek", "Klikněte a získejte dárek"] },
    OWNAppi_linkDescriptionSk: state => { return state.linkDescriptionSk = ["Kliknite a získajte darček", "Kliknite a získajte darček", "Kliknite a získajte darček", "Kliknite a získajte darček", "Kliknite a získajte darček"] },
    OWNAppi_linkDescriptionEn: state => { return state.linkDescriptionEn = ["Click here for a gift", "Click here for a gift", "Click here for a gift", "Click here for a gift", "Click here for a gift"] },
    OWNAppi_Iconcolor1: state => { return { hex: '#813EEF' } },
    OWNAppi_Iconcolor2: state => { return { hex: '#813EEF' } },
    OWNAppi_Iconcolor3: state => { return { hex: '#813EEF' } },
    OWNAppi_Iconcolor4: state => { return { hex: '#813EEF' } },
    OWNAppi_Iconcolor5: state => { return { hex: '#813EEF' } },
    OWNAppi_IconcolorBtn1: state => { return { hex: '#813EEF' } },
    OWNAppi_IconcolorBtn2: state => { return { hex: '#813EEF' } },
    OWNAppi_IconcolorBtn3: state => { return { hex: '#813EEF' } },
    OWNAppi_IconcolorBtn4: state => { return { hex: '#813EEF' } },
    OWNAppi_IconcolorBtn5: state => { return { hex: '#813EEF' } },
    OWNAppi_IconcolorBckBtn1: state => { return { hex: '#ffffff' } },
    OWNAppi_IconcolorBckBtn2: state => { return { hex: '#ffffff' } },
    OWNAppi_IconcolorBckBtn3: state => { return { hex: '#ffffff' } },
    OWNAppi_IconcolorBckBtn4: state => { return { hex: '#ffffff' } },
    OWNAppi_IconcolorBckBtn5: state => { return { hex: '#ffffff' } },
    OWNAppi_showLastTopVariables: state => { return state.showLastTopVariables = [20, 20, 20, 20, 20] }
};

export default {
    state,
    getters
}